# Configuration for CV
person:
  first_name: Vivek
  last_name: Srikrishnan
  title: Assistant Professor
  affiliation: Department of Biological & Environmental Engineering
  affiliation_link: https://bee.cals.cornell.edu
  email: viveks@cornell.edu
  web: https://viveks.bee.cornell.edu
  github: vsrikrish
  googlescholar: CY_JxugAAAAJ
  orcid: 0000-0003-0049-3805
  subject: "climate, systems, engineering"
  address:
    line1: 318 Riley-Robb Hall
    line2: Cornell University
    postcode: Ithaca, NY 14853
    country: USA

paths:
  bib_path: bibliography
  yaml_path: data

publications:
  - title: Papers
    file: library.bib
  - title: Conferences
    file: conferences.bib

sections:
  - title: Research Interests
    file: interests.yml
  - title: Appointments
    file: appointments.yml
  - title: Education
    file: education.yml
  - title: Invited Talks
    file: talks.yml
  - title: Workshops Organized
    file: workshops.yml
  - title: Grants and Contracts
    file: grants.yml
  - title: Networks and Projects
    file: projects.yml
  - title: Teaching
    file: teaching.yml
  - title: Advising
    file: advising.yml
  - title: Awards
    file: awards.yml
  - title: Outreach
    file: outreach.yml
  - title: Service
    file: service.yml
  - title: Professional Experience
    file: experience.yml
