# Configuration for CV
person:
  first_name: Ben
  last_name: Rachunok
  title: Assistant Professor
  affiliation: Edward P. Fitts Department of Industrial and Systems Engineering
  affiliation_link: http://ise.ncsu.edu
  email: barachun@ncsu.edu
  web: http://resilience.wordpress.ncsu.edu
  github: brachunok
  googlescholar: Ct3IhL-MAAAAJ
  orcid: 0000-0001-6405-978X
  subject: "climate, systems, engineering"
  address:
    line1: 915 Partners Way, 4171
    line2: North Carolina State University
    postcode: Raleigh, NC 27606
    country: USA

paths:
  bib_path: bibliography
  yaml_path: data

publications:
  - title: Papers
    file: library.bib
  - title: Conferences
    file: conferences.bib

sections:
  - title: Research Interests
    file: interests.yml
  - title: Appointments
    file: appointments.yml
  - title: Education
    file: education.yml
  - title: Invited Talks
    file: talks.yml
  - title: Workshops Organized
    file: workshops.yml
  - title: Grants and Contracts
    file: grants.yml
  - title: Networks and Projects
    file: projects.yml
  - title: Teaching
    file: teaching.yml
  - title: Advising
    file: advising.yml
  - title: Committee Member
    file: committee.yml
  - title: Awards
    file: awards.yml
  - title: Outreach
    file: outreach.yml
  - title: Service
    file: service.yml
  - title: Professional Experience
    file: experience.yml
